import turtle
turtle.shape("turtle") 
turtle.setup(500,500)
turtle.bgcolor("yellow")
turtle.title("Графіка в мові Python")
turtle.speed(10)
turtle.setpos(-100,-80)
turtle.clear()
turtle.pensize(5)

turtle.color("black","gray")
turtle.begin_fill()
turtle.left(90)
turtle.forward(210)
turtle.right(90)
turtle.forward(190)
turtle.right(90)
turtle.forward(210)
turtle.right(90)
turtle.forward(190)
turtle.end_fill()

turtle.right(90)
turtle.forward(210)

turtle.color("black","blue")
turtle.begin_fill()
turtle.left(90)
turtle.forward(40)
turtle.right(150)
turtle.forward(156)
turtle.right(60)
turtle.forward(156)
turtle.right(150)
turtle.forward(230)
turtle.end_fill()

turtle.up()
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(35)

turtle.color("black","yellow")
turtle.right(90)
turtle.down()
turtle.begin_fill()
for i in range(4):
    turtle.left(90)
    turtle.forward(45)
turtle.end_fill()

turtle.up()
turtle.left(90)
turtle.forward(65)

turtle.color("black","#B00000")
turtle.down()
turtle.begin_fill()
for i in range(2):
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(120)
    turtle.right(90)
turtle.end_fill()

s="Назаренко Олександр"
turtle.up()
turtle.setpos(-100,-130)
turtle.write(s, font=("Arial", 14, "normal"))
turtle.setpos(-100,-145)

print("x",turtle.xcor())
print("y",turtle.ycor())